import { analyzeMatch } from "../../lib/match-analysis";
import type { MatchRole, ProfileResponse } from "../../lib/types";

const roles: MatchRole[] = ["TOP", "JUNGLE", "MIDDLE", "BOTTOM", "UTILITY"];
const names = [
  "Aurelion Sol",
  "Kha'Zix",
  "Nunu & Willump",
  "Miss Fortune",
  "Renata Glasc",
];
const raw = [100, 200].flatMap((teamId) =>
  roles.map((teamPosition, index) => ({
    teamId,
    teamPosition,
    kills: 4,
    deaths: 5,
    assists: 10,
    goldEarned: 12500,
    totalMinionsKilled: 200,
    neutralMinionsKilled: 0,
    visionScore: 35,
    challenges: { laneMinionsFirst10Minutes: 35 },
  })),
);
const items = Array.from({ length: 7 }, (_, i) => ({
  id: 1000 + i,
  icon: "/icon-32.png",
}));

export const profileFixture: ProfileResponse = {
  profile: {
    gameName: "Fake Sun",
    tagLine: "Kite",
    region: "LA2",
    puuid: "fixture",
    summonerLevel: 659,
    profileIcon: "/icon-128.png",
  },
  ranked: [
    {
      queueType: "RANKED_SOLO_5x5",
      queueLabel: "Ranked Solo/Duo",
      tier: "MASTER",
      rank: "I",
      leaguePoints: 1250,
      wins: 10000,
      losses: 9999,
      winRate: 50,
      hotStreak: false,
      tierLabel: "MASTER",
      emblemTier: "MASTER",
    },
    {
      queueType: "RANKED_FLEX_SR",
      queueLabel: "Ranked Flex",
      tier: "DIAMOND",
      rank: "III",
      leaguePoints: 45,
      wins: 24,
      losses: 16,
      winRate: 60,
      hotStreak: false,
      tierLabel: "DIAMOND III",
      emblemTier: "DIAMOND",
    },
  ],
  featuredQueue: null,
  mastery: names.map((name, i) => ({
    id: i,
    name,
    points: 1234567,
    level: 125,
    icon: "/icon-64.png",
  })),
  matches: Array.from({ length: 30 }, (_, i) => ({
    matchId: `LA2_${i}`,
    queueId: 420,
    championName: names[i % 5],
    championIcon: "/icon-64.png",
    role: roles[i % 5],
    win: i % 3 !== 0,
    kills: 4,
    deaths: 5,
    assists: 10,
    kda: "2.80",
    cs: 200,
    killParticipation: 70,
    damage: "24.5k",
    gold: "12.5k",
    duration: "30m 00s",
    visionScore: 35,
    summonerId: "fixture",
    gameEndTimestamp: 1789840000000 - i * 3600000,
    largestMultiKill: 2,
    totalDamageTaken: "18.2k",
    csPerMinute: "6.7",
    goldPerMinute: 417,
    damagePerMinute: 817,
    takenPerMinute: 607,
    spells: [
      { name: "Flash", icon: "/icon-32.png" },
      { name: "Ignite", icon: "/icon-32.png" },
    ],
    items,
    participants: raw.map((player, index) => ({
      puuid: index === i % 5 ? "fixture" : `player-${index}`,
      teamId: player.teamId,
      riotId: index === i % 5 ? "Fake Sun#Kite" : `Player ${index}#TEST`,
      gameName: index === i % 5 ? "Fake Sun" : `Player ${index}`,
      tagLine: index === i % 5 ? "Kite" : "TEST",
      championName: names[index % 5],
      championIcon: "/icon-64.png",
      role: player.teamPosition,
      win: (player.teamId === 100) === (i % 3 !== 0),
      kills: 4,
      deaths: 5,
      assists: 10,
      kda: "2.80",
      damage: 24500 + index * 100,
      items,
    })),
    timeline: { kp: [] },
    analysis: analyzeMatch({
      queueId: 420,
      mapId: 11,
      durationSeconds: 1800,
      participant: raw[i % 5],
      participants: raw,
    }),
  })),
  summary: {
    totalGames: 30,
    winRate: 67,
    kdaRatio: "2.80",
    averageCs: "200",
    averageKillParticipation: "70%",
    averageVision: "35",
    recentForm: "L W W L W",
  },
  championStats: names.map((name) => ({
    name,
    games: 6,
    winRate: 67,
    averageKda: "2.80",
    icon: "/icon-64.png",
  })),
  meta: [],
};
